name: GDC Github CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RESOURCE_GROUP: 'GDC-API-RG'  # Name of the Azure resource group
  LOCATION: 'brazilsouth'  # Azure region where the app will be deployed
  SUBSCRIPTION_ID: '2e8fe762-c52b-4306-87ea-7dbe71bb79a2'  # Azure subscription ID

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Specifies the OS of the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Uses the official GitHub action to clone the repository

    - name: Setup .NET
      uses: actions/setup-dotnet@v1  # Sets up .NET on the runner
      with:
        dotnet-version: '8.0.x'  # Specifies the version of .NET 8 to install

    - name: Restore dependencies
      run: dotnet restore 'GDC-Api.sln'  # Specifies the path to the solution file

    - name: Build
      run: dotnet build 'GDC-Api.sln' --configuration Release --no-restore  # Specifies the path to the solution file

    - name: Publish
      run: dotnet publish 'GDC-Api.sln' --configuration Release --output ${{ github.workspace }}/publish  # Specifies the path to the solution file

    - name: Publish Artifacts - Bicep
      uses: actions/upload-artifact@v2  # Uses the official GitHub action to upload artifacts
      with:
        name: Bicep  # Name of the artifact
        path: infra/webapp.bicep  # Path to the Bicep file to be uploaded as an artifact
