name: GDC-API CI/CD

# Define when to run this workflow
on:
  push: # Triggers the workflow on every push to the 'main' branch
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow from the Actions tab in GitHub

env:
  RESOURCE_GROUP: "GDC-API-RG" # Name of the Azure resource group
  LOCATION: "Brazil South" # Azure region where the app will be deployed (optional, can be changed)
  SUBSCRIPTION_ID: "2e8fe762-c52b-4306-87ea-7dbe71bb79a2" # Azure subscription ID
  WEBAPP_NAME: "GDC-API-WEB-APP" # Globally unique name for the Azure App Service

jobs:
  build-and-deploy: # Name of the job to be executed
    runs-on: ubuntu-latest # Specifies the OS of the runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # Uses the official GitHub action to clone the repository

      - name: Setup .NET
        uses: actions/setup-dotnet@v1 # Sets up .NET on the runner
        with:
          dotnet-version: "8.0.x" # Specifies the version of .NET 8 to install

      - name: Restore dependencies
        run: dotnet restore '**/*.sln' # Restores project dependencies using the solution file (.sln)

      - name: Build
        run: dotnet build '**/*.sln' --configuration Release --no-restore # Builds the solution in Release mode

      - name: Run tests
        run: dotnet test '**/*.csproj' --no-restore --verbosity normal # Runs unit tests in the specified test project

      - name: Publish
        run: dotnet publish '**/*.sln' --configuration Release --output ${{ github.workspace }}/publish # Publishes the app to the 'publish' directory

      - name: "Login via Azure CLI"
        uses: azure/login@v1 # Uses the official Azure action to log in to Azure CLI
        with:
          creds: ${{ secrets.GCD_API_AZURE_CREDENTIALS }} # Uses Azure credentials stored as a secret in GitHub

      - name: Publish Artifacts - Bicep
        uses: actions/upload-artifact@v2 # Uses the official GitHub action to upload artifacts
        with:
          name: Bicep # Name of the artifact
          path: infra/webapp.bicep # Path to the Bicep file to be uploaded as an artifact
